name: Increase Swapfile Action
description: "Increases swap memory by creating and enabling a new swapfile"
inputs:
  swap_size:
    description: "Size of the swapfile (e.g., 6G)"
    required: false
    default: "6G"
runs:
  using: "composite"
  steps:
    - name: Show current swap usage
      shell: bash
      run: sudo swapon --show

    - name: Disable all swap
      shell: bash
      run: sudo swapoff -a

    - name: Allocate swapfile
      shell: bash
      run: sudo fallocate -l ${{ inputs.swap_size }} /swapfile

    - name: Set swapfile permissions
      shell: bash
      run: sudo chmod 600 /swapfile

    - name: Format swapfile as swap
      shell: bash
      run: sudo mkswap /swapfile

    - name: Enable the swapfile
      shell: bash
      run: sudo swapon /swapfile

    - name: Display new swap usage
      shell: bash
      run: sudo swapon --show
