[workspace]
resolver = "2"
members = ["toolkit-rust", "cli", "types"]

[workspace.dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
convert_case = "0.7.1"
home = "0.5.11"
lazy-regex = "3.4.1"
minijinja = "2.7.0"
regex = "1.11.1"
reqwest = "0.12.12"
schemars = "0.8.21"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
warp = "0.3.7"

# === Nexus deps ===
nexus-toolkit = { path = "toolkit-rust" }
nexus-types = { path = "types" }

# === Sui deps ===
[workspace.dependencies.sui_sdk]
git = "https://github.com/MystenLabs/sui"
tag = "testnet-v1.38.1"
package = "sui-sdk"

[workspace.dependencies.move_core_types]
git = "https://github.com/MystenLabs/sui"
tag = "testnet-v1.38.1"
package = "move-core-types"
