[package]
name = "nexus-types"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
lazy-regex.workspace = true
regex.workspace = true
serde.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
