[package]
name = "nexus-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
convert_case.workspace = true
home.workspace = true
minijinja.workspace = true
petgraph.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true

# === Nexus deps ===
[dependencies.nexus-types]
workspace = true
features = ["full"]

[dev-dependencies]
assert_matches = "1.5.0"
schemars.workspace = true
serial_test = "3.2.0"
warp = "0.3.7"

nexus-toolkit.workspace = true
