[package]
name = "nexus-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
colored = "3.0.0"
convert_case = "0.7.1"
home = "0.5.11"
minijinja = "2.7.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"

[dependencies.sui_sdk]
git = "https://github.com/MystenLabs/sui"
tag = "testnet-v1.38.1"
package = "sui-sdk"

[dependencies.move_core_types]
git = "https://github.com/MystenLabs/sui"
tag = "testnet-v1.38.1"
package = "move-core-types"

[dev-dependencies]
assert_matches = "1.5.0"
