name: Install pre-commit dependencies
description: Install pre-commit dependencies

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.13.0
      with:
        toolchain: nightly-2025-01-06, stable
        override: true
        components: rustfmt, clippy
        cache: 'false'

    # For more tools, see: https://github.com/taiki-e/install-action/blob/main/TOOLS.md
    - name: Install Rust tools
      uses: taiki-e/install-action@v2.57.8
      with:
        tool: cargo-binstall,just,cargo-nextest,typos

    - name: Install NPM stuff from helpers/npm-install-g.txt
      shell: bash
      run: ./helpers/npm-install-g.sh
