name: Audit Dependencies
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  detect-changes:
    uses: ./.github/workflows/detect_changes.yml
    with:
      files: |
        **/Cargo.toml
        **/Cargo.lock
        **/audit.toml

  audit:
    name: Audit Dependencies
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true' && ( github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@v1
