# Github workflow to build and test the Nexus CLI code

name: Nexus CLI
on:
  pull_request:
    paths:
      - "cli/**"
      - ".github/workflows/cli.yml"
  push:
    branches:
      - main
    paths:
      - "cli/**"
      - ".github/workflows/cli.yml"

jobs:
  # 1. Install Rust
  # 2. Install Rust cache
  # 3. Install just
  # 4. Build, fmt, clippy and test the CLI
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # 1.
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # 2.
      - name: Cache Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      # 3
      - uses: taiki-e/install-action@just

      # 4
      - run: just cli check
      - run: just cli fmt-check
      - run: just cli clippy
      - run: just cli test
