name: CI Coverage Check

on:
  pull_request:
    paths:
      - cli/**
      - sdk/**
      - toolkit-rust/**
      - tools/**
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Coverage
        uses: ./.github/actions/coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          cache-key-suffix: -pr-${{ github.event.pull_request.number }}
