name: Update Coverage Baseline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-baseline:
    runs-on: ubuntu-latest
    name: Update Coverage Baseline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for relevant file changes
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: |
            cli/**
            sdk/**
            toolkit-rust/**
            tools/**

      - name: Run Coverage
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/coverage
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          codecov-flags: unittests,baseline
          codecov-name: main-baseline
          cache-key-suffix: -main-baseline
