name: CI Coverage Check

on:
  pull_request:
    paths:
      - cli/**
      - sdk/**
      - toolkit-rust/**
      - tools/**

# Fix for OOM.
env:
  CARGO_BUILD_JOBS: 1
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: >
    -C codegen-units=1

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Cache Cargo Registry and Build Artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}-cargo-pr-${{ github.event.pull_request.number }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.5

      - name: Install cargo-llvm-cov
        run: cargo binstall cargo-llvm-cov --force

      - name: Generate Coverage
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        env:
          CARGO_TERM_COLOR: always
          CACHE_ON_FAILURE: true
          CARGO_INCREMENTAL: 0

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
