name: Lint and Format Markdown

on:
  pull_request:

permissions:
  contents: write

jobs:
  detect-changes:
    uses: ./.github/workflows/detect_changes.yml
    with:
      files: |
        **/*.md

  lint-format:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: github.event.pull_request.head.repo.full_name == github.repository && needs.detect-changes.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: ${{ needs.detect-changes.outputs.all_changed_files }}
          config: .markdownlint.json
          fix: true

      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.DEVOPS_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEVOPS_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "Talus DevOps"
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_message: "style: format markdown files"

  typos-check:
    needs: [lint-format, detect-changes]
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository && needs.detect-changes.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for typos
        uses: crate-ci/typos@v1.32.0
        with:
          files: ${{ needs.detect-changes.outputs.all_changed_files }}
