name: Lint and Format Markdown

on:
  pull_request:

permissions:
  contents: write

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          **/*.md

    - uses: DavidAnson/markdownlint-cli2-action@v20
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        config: .markdownlint.json
        fix: true

    - name: "Import GPG key"
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        gpg_private_key: ${{ secrets.DEVOPS_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.DEVOPS_GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_config_global: true

    - name: "Commit and push changes"
      uses: stefanzweifel/git-auto-commit-action@v5
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        commit_user_name: "Talus DevOps"
        commit_user_email: ${{ steps.import-gpg.outputs.email }}
        commit_message: "style: format markdown files"

  typos-check:
    needs: lint-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: tj-actions/changed-files@v46
      id: changed-files
      with:
        files: |
          **/*.md

    - name: Check for typos
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: crate-ci/typos@v1.32.0
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}