# Github workflow to build and test the Nexus Types library code

name: Nexus Types library
on:
  pull_request:
    paths:
      - "types/**"
      - ".github/workflows/types.yml"
  push:
    branches:
      - main
    paths:
      - "types/**"
      - ".github/workflows/types.yml"

jobs:
  # 1. Install Rust
  # 2. Install Rust cache
  # 3. Install just
  # 4. Build, fmt, clippy and test the Nexus Types library
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # 1.
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable, nightly
          override: true
          components: rustfmt, clippy

      # 2.
      - name: Cache Build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: types

      # 3.
      - uses: taiki-e/install-action@just

      # 4
      - run: cargo +stable --version
      - run: cargo +nightly --version
      - run: just types check
      - run: just types fmt-check
      - run: just types clippy
      - run: just types test
