[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars.workspace = true
serde.workspace = true
tokio.workspace = true

# === Nexus deps ===
nexus-toolkit.workspace = true
nexus-types.workspace = true
